name: capture_flutter
description: Flutter plugin for Capture, the SDK for auto-capturing high quality images of identity documents in a user-friendly way.
version: 1.4.3
homepage: https://microblink.com

environment:
  sdk: ^3.5.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.microblink.capture.flutter
        pluginClass: CaptureFlutterPlugin
      ios:
        pluginClass: CaptureFlutterPlugin